# Accelerate 多卡训练配置（示例）
# 根据实际硬件调整 num_processes 和 gpu_ids
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU          # 单卡改为 NO
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4                      # 使用的 GPU 数量
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
